version: "3.9"
services:
  ui:
    image: "tasks-ui-server"
    ports:
      - "8080:8080"
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"
      - "14250:14250"